default: &default
  adapter: postgresql
  pool: 5
  username: db_user
  password: hello
  timeout: 5000

development:
  <<: *default
  host: db
  database: bingo_dev

production:
  <<: *default
  database: bingo_prod
